# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.

[[main]]
  name = "Artigos"
  pageRef = "post"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Privacy"
#   pageRef = "privacy"
